name: chit_chat
description: A Demo Chat Application on the @protocol.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_app_flutter: 2.0.0
  at_chat_flutter: ^3.0.1
  at_client: ^3.0.0
  at_client_mobile: ^3.0.0
  at_contact: ^3.0.1
  at_contacts_flutter: ^3.0.0
  at_onboarding_flutter: ^3.0.1
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  google_fonts: ^2.1.0
  permission_handler: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
